version: "2"
plugins:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
checks:
  argument-count:
    enabled: true
  file-lines:
    enabled: true
  class-coupling:
    enabled: true
ratings:
  paths:
    - "app/**/*.rb"
exclude_paths:
  - 'config/'
  - 'db/'
  - 'public/'
  - 'spec/'
  - 'vendor/'
