name: Code Climate Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0      # Replace with your Ruby version

      - name: Install Dependencies
        run: |
          bundle install
          gem install codeclimate-test-reporter

      - name: Run Code Analysis
        run: |
          curl -L https://github.com/codeclimate/codeclimate/releases/latest/download/codeclimate.tar.bz2 | tar xj
          sudo mv codeclimate /usr/local/bin/
          codeclimate analyze

      - name: Run Tests with Coverage
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: |
          bundle exec test
          codeclimate-test-reporter
