name: Code Climate Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0  # Replace with your Ruby version

      - name: Install Dependencies
        run: |
          bundle install
          gem install codeclimate-test-reporter

      - name: Install CodeClimate CLI
        run: |
          curl -L https://github.com/codeclimate/codeclimate/releases/latest/download/codeclimate-linux-amd64 -o /tmp/codeclimate
          ls -l /tmp/codeclimate
          chmod +x /tmp/codeclimate
          sudo mv /tmp/codeclimate /usr/local/bin/codeclimate

      - name: Set Up Database
        run: |
          bundle exec rails db:setup
          bundle exec rails db:test:prepare

      - name: Run Tests with Coverage
        env:
          SIMPLECOV_CODECLIMATE: true  # Enables CodeClimate-compatible output
        run: |
          bundle exec rails test

      - name: Format Coverage (if needed for parallelized tests)
        run: |
          codeclimate-test-reporter format-coverage --coverage-input-type simplecov --coverage-input-path coverage/.resultset.json

      - name: Sum Coverage (if needed for parallelized tests)
        run: |
          codeclimate-test-reporter sum-coverage --input-type simplecov --output-path coverage/final_report.json

      - name: Upload Coverage to Code Climate
        env:
          CODECLIMATE_REPO_TOKEN: "62389695e502022682d5ad2c68bc00b99ab5686f9103745e049f66d6bb0da56e"
        run: |
          codeclimate-test-reporter upload-coverage

      - name: Run Code Analysis
        run: |
          codeclimate analyze
