name: Code Climate Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0      # Replace with your Ruby version

      - name: Install Dependencies
        run: |
          bundle install
          gem install codeclimate-test-reporter

      - name: Run Code Analysis
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/qltysh/qlty/releases/download/v0.460.0/qlty-installer.sh | sh
          sudo mv codeclimate /usr/local/bin/
          codeclimate analyze

      - name: Run Tests with Coverage
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: |
          bundle exec bin/rails db:test:prepare test test:system
          codeclimate-test-reporter
