name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install dependencies
        run: |
          bundle install
          gem install codeclimate-test-reporter

      - name: Install Code Climate test reporter
        run: |
          curl -L https://github.com/codeclimate/test-reporter/releases/download/v1.0.0/cc-test-reporter-linux-amd64 > /usr/local/bin/cc-test-reporter
          chmod +x /usr/local/bin/cc-test-reporter

      - name: Verify cc-test-reporter installation
        run:
          ls /usr/local/bin
          cc-test-reporter --version

      - name: Checking Test Reporter
        run: ls /usr/local/bin/cc-test-reporter

      - name: Prepare coverage report
        run: |
          cc-test-reporter before-build

      - name: Run tests
        run: |
          bundle exec bin/rails db:test:prepare
          bundle exec bin/rails test

      - name: Format coverage
        run: |
          cc-test-reporter format-coverage --coverage-input-type simplecov --coverage-input-path coverage/coverage.json

      - name: Upload coverage
        run: |
          cc-test-reporter upload-coverage

    env:
      GIT_COMMIT_SHA: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref }}
