name: Code Climate Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0      # Replace with your Ruby version

      - name: Install Dependencies
        run: |
          bundle install
          gem install codeclimate-test-reporter

      - name: Install CodeClimate CLI
        run: |
          curl -L -o codeclimate.tar.bz2 https://github.com/codeclimate/codeclimate/releases/download/0.85.14/codeclimate.tar.bz2
          tar xjf codeclimate.tar.bz2
          sudo mv codeclimate /usr/local/bin/
          rm codeclimate.tar.bz2
          codeclimate --version  # Verify installation

      - name: Run Code Analysis
        run: |
          codeclimate analyze

      - name: Run Tests with Coverage
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: |
          bundle exec bin/rails db:test:prepare
          bundle exec rspec
          codeclimate-test-reporter
