name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install dependencies
        run: |
          bundle install
          gem install codeclimate-test-reporter

      - name: Install Code Climate test reporter
        run: |
          curl -L https://github.com/codeclimate/codeclimate/releases/latest/download/codeclimate-linux-amd64 -o /tmp/codeclimate
          ls -l /tmp/codeclimate
          chmod +x /tmp/codeclimate
          sudo mv /tmp/codeclimate /usr/local/bin/codeclimate

      - name: Verify cc-test-reporter installation
        run: cc-test-reporter --version

      - name: Prepare coverage report
        run: |
          codeclimate before-build

      - name: Run tests
        run: |
          bundle exec bin/rails db:test:prepare
          bundle exec bin/rails test

      - name: Format coverage
        run: |
          codeclimate format-coverage --coverage-input-type simplecov --coverage-input-path coverage/coverage.json

      - name: Upload coverage
        run: |
          codeclimate upload-coverage

    env:
      GIT_COMMIT_SHA: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref }}
